# Generated by Django 4.0.4 on 2022-06-19 18:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('etu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='users.etudiant')),
                ('inv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='users.investisseur')),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du Projet')),
                ('categorie', models.CharField(max_length=200, verbose_name='categorie projet')),
                ('media', models.FileField(blank=True, upload_to='documents/post_doc/')),
                ('image', models.ImageField(blank=True, default='post.jpg', upload_to='image/post_image/')),
                ('investi', models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=10)),
                ('description', models.TextField(max_length=500)),
                ('date_post', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='date_post')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projet', to='users.etudiant')),
            ],
        ),
    ]
