# Generated by Django 4.0.4 on 2022-06-21 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_alter_message_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corps', models.TextField(max_length=500)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corps', models.TextField(max_length=500)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('commentaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='posts.commentaire')),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.AlterModelOptions(
            name='projet',
            options={'ordering': ['-date_post']},
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='projet',
            name='categorie',
            field=models.CharField(choices=[('INFORMATIQUE', 'INFORMATIQUE'), ('AGRICULTURE', 'AGRICULTURE'), ('ELEVAGE', 'ELEVAGE'), ('SANTE', 'SANTE'), ('AUTRES', 'AUTRES')], default='categorie', max_length=200, verbose_name='categorie projet'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='date_post',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date_post'),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.projet'),
        ),
    ]
