# Generated by Django 4.0.4 on 2022-06-22 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_commentaire_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commessage',
            name='id_projet',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
