# Generated by Django 4.0.4 on 2022-06-23 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_favoris'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoris',
            name='id_proj',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='favoris',
            name='id_usr',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
