# Generated by Django 4.0.4 on 2022-06-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_etudiant_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investisseur',
            name='entreprise',
            field=models.CharField(blank=True, default='Non renseigné', max_length=100),
        ),
    ]
